#!/bin/bash
#软件安装完后，执行该Shell脚本，一般用来配置软件执行环境
#可以添加systemctl的启动服务

USER_NAME=$(getent passwd `who` | head -n 1 | cut -d : -f 1)
echo "USER_NAME=$USER_NAME"
sed -i -r 's/^User=.*/User='"$USER_NAME"'/g' /usr/lib/systemd/system/ep-qrcode-loc.service
sed -i -r 's/^Group=.*/Group='"$USER_NAME"'/g' /usr/lib/systemd/system/ep-qrcode-loc.service

#检查目标配置文件是否存在，不存在则拷贝一份，存在则啥都不干
if [ ! -f /var/xmover/params/ep-qrcode-loc/ep-qrcode-loc.yaml ]; then
 mkdir -p /var/xmover/params/ep-qrcode-loc
 echo "copy params file ep-qrcode-loc.yaml"
 cp /opt/xmover/ros/melodic/ep_qrcode_loc/share/ep_qrcode_loc/config/ep-qrcode-loc.yaml /var/xmover/params/ep-qrcode-loc/ep-qrcode-loc.yaml
 chmod 777 /var/xmover/params/ep-qrcode-loc/ep-qrcode-loc.yaml
fi

#检查库位表文件是否存在，不存在则拷贝一份，存在则啥都不干
if [ ! -f /var/xmover/params/ep-qrcode-loc/SiteTable.csv ]; then
 mkdir -p /var/xmover/params/ep-qrcode-loc
 echo "copy params file SiteTable.csv"
 cp /opt/xmover/ros/melodic/ep_qrcode_loc/share/ep_qrcode_loc/config/SiteTable.csv /var/xmover/params/ep-qrcode-loc/SiteTable.csv
 chmod 777 /var/xmover/params/ep-qrcode-loc/SiteTable.csv
fi

#检查库位表文件是否存在，不存在则拷贝一份，存在则啥都不干
if [ ! -f /var/xmover/params/ep-qrcode-loc/CaptureTable.csv ]; then
 mkdir -p /var/xmover/params/ep-qrcode-loc
 echo "copy params file CaptureTable.csv"
 cp /opt/xmover/ros/melodic/ep_qrcode_loc/share/ep_qrcode_loc/config/CaptureTable.csv /var/xmover/params/ep-qrcode-loc/CaptureTable.csv
 chmod 777 /var/xmover/params/ep-qrcode-loc/CaptureTable.csv
fi

mkdir -p /var/xmover/log/QR_code_loc

chown -R $USER_NAME:$USER_NAME /opt/xmover
chown -R $USER_NAME:$USER_NAME /var/xmover
chown $USER_NAME:$USER_NAME /usr/lib/systemd/system/ep-qrcode-loc.service

systemctl daemon-reload
systemctl enable ep-qrcode-loc  # disable  开机自启
systemctl start ep-qrcode-loc   # 安装后立即启动
