################################################
#####        params for ep_qrcode_loc                       #######
#####        yuanxun@ep-ep.com                              #######
#####        updateTime:  2024.05.01                              #######
################################################

ep_qrcode_loc:
  verision: "v-0.0.1"
  
  # 运行模式
  mode: 1   # 1:采集二维码坐标; 
            # 2:计算qrmap2mapTrans; 
            # 3:论速计递推运行；

  # 最终发布的消息  # covariance[0]: 此帧数据是否可用，0：不可用 1：可用
                  # covariance[1]: 此帧数据不可用的原因：0：离开运行区域 1：递推长度超出限制
                  # covariance[2]: 此帧数据来源，0：二维码 1：轮速计递推
  odomMapBase: "ep_qrcode_loc/odometry/base" # nav_msgs::Odometry类型
  odomMapCamera: "ep_qrcode_loc/odometry/locCamera" # nav_msgs::Odometry类型

  pathMapBase: "ep_qrcode_loc/path/base"
  pathMapCamera: "ep_qrcode_loc/path/locCamera"

  # 测试用消息
  odomQrmapBase: "ep_qrcode_loc/qrmap/odometry/base"
  odomQrmapCamera: "ep_qrcode_loc/qrmap/odometry/locCamera"
  msgTopic: "ep_qrcode_loc/msg"

  realVelDt: 0.01 
  show_msg: false
  collect_QRcode: true

  # 最大递推距离
  maxEstimationDis: 2.0

  # 相机网络所用端口
  port: 1024

  # 文件路径
  log_dir: "/home/zl/work/ep-qrcode-loc/src/ep_qrcode_loc/log/"
  cfg_dir: "/home/zl/work/ep-qrcode-loc/src/ep_qrcode_loc/config/"

  # 论速记补偿系数
  realVelRatio_x: 1.035 #0.93458
  realVelRatio_z: 1.0
  realVelOffset_x: 0.0
  realVelOffset_z: 0.0

  yawAverageNum: 15

  # lidar坐标系与二维码坐标系之间的转换关系 #(t_x, t_y, t_z, q_x, q_y, q_z, q_w)
  qrmap2mapTrans: [-81.6888, 36.602, 0, 0, 0, -0.0142877, 0.999898]
  #qrmap2mapTrans: [0, 0, 0, 0, 0, 0, 1]

  # 启用二维码定位的区域，顶点首尾相接组成一个多边形区域[x1,y1, x2,y2, ....]
  # enableArea: [ 0.37, 0.685, 
  #               0.37, 5.685, 
  #               5.37, 5.685, 
  #               5.37, 0.685]

  enableArea: [ 300, -173, 
                350, -173, 
                350, -200, 
                300, -200]

  detect_site_dis: 1.8
  aux_site_dis: 1.365
  forkaction_site_dis: 0.93
  site_site_dis: 1.36

#rosbag record /lslidar_trans_points /imu /tf_static /ep_qrcode_loc/odometry/base
  