###################################################################################
#####        params for ep_qrcode_loc
#####           yuanxun@ep-ep.com
#####        updateTime:  2024.05.01
###################################################################################

ep_qrcode_loc:
#----------------------------------------------------------------------------------
  # 运行模式1:采集二维码坐标（长时间停在二维码上方）; 
  # 运行模式2:采集二维码编号（快速扫过）；
  # 运行模式3:正常运行；
  # 运行模式4:只扫码,不递推,用于测试；
  operating_mode: 3

#----------------------------------------------------------------------------------
  # 日志级别 "FATAL" "ERROR" "WARN" "INFO" "DEBUG"
  logLevel: "DEBUG"

#----------------------------------------------------------------------------------
  # 调试程序过程中用到参数
  show_original_msg: false # 记录和发布相机扫到二维码的原始信息
  is_pub_tf: false # 后续删除相关参数和代码
  ignore_area: true # 无视可运行区域限制

#----------------------------------------------------------------------------------
  # 低速界限,运行模式3中,高于该速度时每次只取一帧二维码数据
  low_speed_UL: 0.1

#----------------------------------------------------------------------------------
  # 最大递推距离,超多该距离则将输出帧标记为不可用
  maxEstimationDis: 1.1 

#----------------------------------------------------------------------------------
  # 相机网络所用端口,与相机内设置的一致
  port: 1024

#----------------------------------------------------------------------------------
  # 轮速记补偿系数
  realVelRatio_x: 1.035 #0.93458
  realVelRatio_z: 1.0
  realVelOffset_x: 0.0
  realVelOffset_z: 0.0

#----------------------------------------------------------------------------------
  # lidar坐标系与二维码坐标系之间的转换关系 #(t_x, t_y, t_z, q_x, q_y, q_z, q_w)
  qrmap2mapTrans: [0, 0, 0, 0, 0, 0, 1]

#----------------------------------------------------------------------------------
  # 启用二维码定位的区域，顶点首尾相接组成一个多边形区域[x1,y1, x2,y2, ....]
  enableArea: [ -4.181, 3.940, 
                27.869, 4.508, 
                28.011, -13.198
                -4.037, -13.065]
                
#----------------------------------------------------------------------------------
  # 库位设置中的相关尺寸
  detect_site_dis: 1.9      # 识别点距离
  aux_site_dis: 1.4         # 辅助点距离
  forkaction_site_dis: 0.93 # 货叉动作点距离
  site_site_dis: 1.36       # 库位前后距离