################################################
#####        params for ep_qrcode_loc                       #######
#####        yuanxun@ep-ep.com                              #######
#####        updateTime:  2024.05.01                              #######
################################################

ep_qrcode_loc:
  verision: "v-0.0.1"
  
  odom4mapTopic: "ep_qrcode_loc/odom_map"
  odom4qrmapTopic: "ep_qrcode_loc/odom_qrmap"
  msgTopic: "ep_qrcode_loc/msg"
  useLidar: false  #true:实施阶段使用Lidar采集二维码坐标
  calTrans: false  #true:实施阶段使用Lidar采集二维码坐标
  mode: 3   # 1:采集二维码坐标; 2:计算qrmap2mapTrans; 3:正常运行
  show_msg: false
  collect_QRcode: true
  port: 1024
  log_dir: "/home/zl/work/ep-qrcode-loc/src/ep_qrcode_loc/log/"
  cfg_dir: "/home/zl/work/ep-qrcode-loc/src/ep_qrcode_loc/config/"

  #qrmap2mapTrans: [26.0745, 2.03618, 0, 0, 0, 0.999419, -0.0340756] #(t_x, t_y, t_z, q_x, q_y, q_z, q_w)
  # qrmap2mapTrans: [11.4943, -0.0305323, 0, 0, 0, 0.999919, 0.0127641] #(t_x, t_y, t_z, q_x, q_y, q_z, q_w)
  # qrmap2mapTrans: [11.5092, -0.0253609, 0, 0, 0, 0.999919, 0.0127504] #(t_x, t_y, t_z, q_x, q_y, q_z, q_w)
  # qrmap2mapTrans: [11.4888, -0.0223434, 0, 0, 0, 0.999919, 0.0127218] #(t_x, t_y, t_z, q_x, q_y, q_z, q_w)
  qrmap2mapTrans: [311.613, -188.321, 0, 0, 0, -0.717352, 0.696711] #(t_x, t_y, t_z, q_x, q_y, q_z, q_w)
  
  